# Generated by Django 2.2.18 on 2021-09-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_auto_20210724_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=50)),
                ('meeting_time', models.TimeField(blank=True, null=True)),
                ('meeting_Day', models.CharField(blank=True, max_length=10, null=True)),
                ('students', models.ManyToManyField(to='student.Student')),
            ],
        ),
    ]
