# Generated by Django 2.2.18 on 2021-09-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0034_studentclub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentclub',
            old_name='meeting_Day',
            new_name='meeting_day',
        ),
    ]
